### ISSUE TITLE
How to edit settings for first start?

### ISSUE THREAD

**Issue by bolshukhin** [alterrebe/docker-mail-relay#13]
I'm using Docker for windows. How I must to edit setting? Thanks

**Comment by alterrebe** [comment]
I don't have access to Docker-for-Windows right now, but I believe it should be quite the same - you can use command line or Docker-Compose file to define environment variables and that's it.

BTW, the specific docker container is intended to simplify connecting other applications running inside K8s cluster (or outside the cluster, but still within the VPC) to send email using AWS SES. You can run the container locally if you develop some software, but I'd **not** recommend to use it a mail gateway for your LAN - it opens wide possibilities for misuse.
