### ISSUE TITLE
How to see logs? How to empty the queue?

### ISSUE THREAD

**Issue by PaulBunkey** [alterrebe/docker-mail-relay#16]
Hi,
I'd like to run this in production, so I'd like to know how to troubleshoot this service. So several questions about maintenance:
 - Where do I find logs?
 - How do I see what stuck in the queue?
 - How to retry the queue?
 - How do I reset/empty the queue?

**Comment by alterrebe** [comment]
It would be great to improve the documentation including answers to these and other questions. I hope that it will be eventually done, but I can't promise the date. I use the image in production for almost ten years w/o any issues, but
- only as a relay for AWS SES inside VPC for a few internal servers;
- with a rather small number of messages.

I never had the queue stuck as long as the AWS SES credentials not expired, neither I needed to reset or retry the queue.
